// Report Types and Interfaces
export type ReportType = 'FINANCIAL' | 'PAYROLL' | 'EMPLOYEE' | 'SITE' | 'EXPENSE' | 'REVENUE' | 'CUSTOM' | 'RECEIPT' | 'INVOICE'
export type ReportStatus = 'GENERATING' | 'COMPLETED' | 'FAILED' | 'QUEUED' | 'CANCELLED'
export type ReportFormat = 'PDF' | 'EXCEL' | 'CSV' | 'JSON'
export type Language = 'EN' | 'AR'
export type PaymentStatus = 'PAID' | 'UNPAID' | 'PARTIAL' | 'OVERDUE'

export interface DateRange {
  start: string
  end: string
}

export interface Report {
  id: string
  title: string
  type: ReportType
  description: string
  dateRange: DateRange
  generatedBy: string
  generatedAt: string
  updatedAt?: string
  status: ReportStatus
  format: ReportFormat
  fileSize?: string
  language: Language
  filePath?: string
  downloadUrl?: string
  shareUrl?: string
  metadata?: ReportMetadata
  error?: ReportError
}

export interface ReportMetadata {
  totalRecords?: number
  dataSourcesUsed?: string[]
  filters?: ReportFilters
  scheduledReport?: boolean
  autoGenerated?: boolean
  version?: number
}

export interface ReportError {
  code: string
  message: string
  details?: string
  timestamp: string
  retryable: boolean
}

export interface ReportFilters {
  siteIds?: string[]
  employeeIds?: string[]
  clientIds?: string[]
  categories?: string[]
  amountRange?: { min: number; max: number }
  dateRange?: DateRange
  paymentStatus?: PaymentStatus[]
  customFilters?: Record<string, any>
}

// Site Data Types
export interface Site {
  id: string
  name: string
  location: string
  type: 'CONSTRUCTION' | 'OFFICE' | 'WAREHOUSE' | 'RETAIL'
  status: 'ACTIVE' | 'INACTIVE' | 'COMPLETED'
  startDate: string
  endDate?: string
  budget: number
  spent: number
  progress: number
  manager: string
  employees: string[]
  address: {
    street: string
    city: string
    state: string
    zip: string
    country: string
  }
  coordinates?: {
    lat: number
    lng: number
  }
}

// Employee Data Types
export interface Employee {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
  position: string
  department: string
  siteId?: string
  salary: number
  hireDate: string
  status: 'ACTIVE' | 'INACTIVE' | 'TERMINATED'
  workSchedule: {
    hoursPerWeek: number
    daysPerWeek: number
  }
  address: {
    street: string
    city: string
    state: string
    zip: string
    country: string
  }
  emergencyContact: {
    name: string
    phone: string
    relationship: string
  }
}

// Payroll Data Types
export interface PayrollRecord {
  id: string
  employeeId: string
  payPeriod: {
    start: string
    end: string
  }
  hoursWorked: number
  overtimeHours: number
  baseSalary: number
  overtimePay: number
  bonuses: number
  deductions: number
  grossPay: number
  netPay: number
  taxes: {
    federal: number
    state: number
    social: number
    medicare: number
  }
  benefits: {
    health: number
    dental: number
    retirement: number
  }
  payDate: string
  status: 'PENDING' | 'PROCESSED' | 'PAID'
}

// Financial Data Types
export interface Expense {
  id: string
  title: string
  description: string
  amount: number
  category: string
  siteId?: string
  employeeId?: string
  date: string
  receiptUrl?: string
  approved: boolean
  approvedBy?: string
  approvedAt?: string
  tags: string[]
}

export interface Revenue {
  id: string
  title: string
  description: string
  amount: number
  clientId: string
  siteId?: string
  date: string
  invoiceNumber?: string
  paymentStatus: PaymentStatus
  dueDate?: string
  paidDate?: string
  category: string
  tags: string[]
}

export interface Safe {
  id: string
  name: string
  type: 'CASH' | 'BANK' | 'INVESTMENT'
  balance: number
  currency: string
  location?: string
  lastUpdated: string
  transactions: SafeTransaction[]
}

export interface SafeTransaction {
  id: string
  type: 'DEPOSIT' | 'WITHDRAWAL' | 'TRANSFER'
  amount: number
  description: string
  date: string
  relatedEntityId?: string
  relatedEntityType?: 'EXPENSE' | 'REVENUE' | 'PAYROLL'
}

// Client Data Types
export interface Client {
  id: string
  name: string
  company?: string
  email: string
  phone: string
  address: {
    street: string
    city: string
    state: string
    zip: string
    country: string
  }
  totalPaid: number
  totalOwed: number
  paymentHistory: ClientPayment[]
  projects: string[]
  status: 'ACTIVE' | 'INACTIVE'
  createdAt: string
}

export interface ClientPayment {
  id: string
  amount: number
  date: string
  description: string
  method: 'CASH' | 'CARD' | 'BANK_TRANSFER' | 'CHECK'
  receiptNumber?: string
  status: PaymentStatus
}

// Receipt/Invoice Types
export interface Receipt {
  id: string
  receiptNumber: string
  clientId: string
  clientName: string
  items: ReceiptItem[]
  subtotal: number
  tax: number
  discount: number
  total: number
  amountPaid: number
  balance: number
  issueDate: string
  dueDate?: string
  paymentStatus: PaymentStatus
  paymentMethod?: string
  notes?: string
  language: Language
}

export interface ReceiptItem {
  id: string
  description: string
  quantity: number
  unitPrice: number
  total: number
  category?: string
}

// Company Information
export interface CompanyInfo {
  name: string
  logo?: string
  address: {
    street: string
    city: string
    state: string
    zip: string
    country: string
  }
  contact: {
    phone: string
    email: string
    website?: string
  }
  taxId?: string
  registration?: string
}

// Report Generation Options
export interface ReportGenerationOptions {
  format: ReportFormat
  language: Language
  includeLogo: boolean
  includeCharts: boolean
  includeDetails: boolean
  customBranding?: {
    primaryColor: string
    secondaryColor: string
    fontFamily: string
  }
  filters?: ReportFilters
  templateId?: string
}

// Report Template
export interface ReportTemplate {
  id: string
  name: string
  type: ReportType
  description: string
  fields: ReportField[]
  layout: ReportLayout
  defaultFilters?: ReportFilters
  supportedFormats: ReportFormat[]
  supportedLanguages: Language[]
}

export interface ReportField {
  id: string
  label: string
  type: 'TEXT' | 'NUMBER' | 'DATE' | 'CURRENCY' | 'PERCENTAGE' | 'LIST'
  required: boolean
  defaultValue?: any
  validation?: FieldValidation
}

export interface FieldValidation {
  min?: number
  max?: number
  pattern?: string
  message?: string
}

export interface ReportLayout {
  header: LayoutSection
  body: LayoutSection
  footer: LayoutSection
  styling: ReportStyling
}

export interface LayoutSection {
  elements: LayoutElement[]
  height?: number
  padding?: number[]
}

export interface LayoutElement {
  type: 'TEXT' | 'IMAGE' | 'TABLE' | 'CHART' | 'LINE'
  content?: string
  style?: ElementStyle
  position?: Position
  size?: Size
}

export interface ElementStyle {
  fontSize?: number
  fontWeight?: 'normal' | 'bold'
  color?: string
  backgroundColor?: string
  textAlign?: 'left' | 'center' | 'right'
  border?: BorderStyle
}

export interface BorderStyle {
  width: number
  color: string
  style: 'solid' | 'dashed' | 'dotted'
}

export interface Position {
  x: number
  y: number
}

export interface Size {
  width: number
  height: number
}

export interface ReportStyling {
  primaryColor: string
  secondaryColor: string
  fontFamily: string
  fontSize: number
  margin: number[]
  pageSize: 'A4' | 'LETTER' | 'A3'
  orientation: 'portrait' | 'landscape'
}

// Custom Report Builder Types
export interface CustomReportConfig {
  title: string
  description: string
  type: ReportType
  dateRange: DateRange
  filters: ReportFilters
  fields: string[]
  groupBy?: string[]
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
  format: ReportFormat
  language: Language
  includeCharts: boolean
  includeDetails: boolean
}

// Automatic Report Types
export interface AutoReportSchedule {
  id: string
  name: string
  type: ReportType
  frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'QUARTERLY' | 'YEARLY'
  dayOfWeek?: number
  dayOfMonth?: number
  time: string
  enabled: boolean
  lastRun?: string
  nextRun: string
  config: CustomReportConfig
  recipients?: string[]
}

// Statistics and Analytics
export interface ReportStats {
  totalReports: number
  completedReports: number
  failedReports: number
  generatingReports: number
  averageGenerationTime: number
  mostGeneratedType: ReportType
  totalDownloads: number
  reportsThisMonth: number
  reportsThisWeek: number
}

// Search and Filter Types
export interface ReportSearchCriteria {
  query?: string
  type?: ReportType
  status?: ReportStatus
  format?: ReportFormat
  language?: Language
  dateRange?: DateRange
  generatedBy?: string
  sortBy?: 'title' | 'type' | 'generatedAt' | 'status'
  sortOrder?: 'asc' | 'desc'
  page?: number
  limit?: number
}

export interface PaginatedReports {
  reports: Report[]
  total: number
  page: number
  limit: number
  totalPages: number
}
