// Icon mappings from MUI to Lucide React
import {
  Plus as Add,
  Edit as Edit,
  Trash2 as Delete,
  Eye as Visibility,
  Briefcase as Assignment,
  Calendar as Schedule,
  Users as Group,
  TrendingUp,
  Flag as Flag,
  CheckSquare as Task,
  AlertTriangle as Warning,
  CheckCircle as CheckCircle,
  Clock as AccessTime,
  Calendar as CalendarToday,
  User as Person,
  DollarSign as AttachMoney,
  FileText as Description,
  ChevronDown as ExpandMore,
  Filter as FilterList,
  Search,
  Download as GetApp,
  BarChart3 as BarChart,
  LayoutDashboard as Dashboard,
  Settings,
  Building2 as Building,
  Wrench as Build,
  Package as Inventory,
  AlertCircle as Error,
  Info,
  Home,
  Menu,
  X as Close,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  MoreHorizontal as MoreHoriz,
  Phone,
  Mail,
  MapPin as LocationOn,
  Star,
  Heart as Favorite,
  Share,
  Bookmark,
  MessageSquare as Chat,
  Bell as Notifications,
  LogOut as ExitToApp,
  RefreshCw as Refresh,
  Upload,
  Copy,
  ExternalLink as OpenInNew,
  Printer as Print,
  Maximize2 as Fullscreen,
  Minimize2 as FullscreenExit,
  Volume2 as VolumeUp,
  VolumeX as VolumeOff,
  Play as PlayArrow,
  Pause,
  Square as Stop,
  SkipForward as SkipNext,
  SkipBack as SkipPrevious,
} from 'lucide-react'

// Export all icons with their MUI names for easy replacement
export {
  Add,
  Edit,
  Delete,
  Visibility,
  Assignment,
  Schedule,
  Group,
  TrendingUp,
  Flag,
  Task,
  Warning,
  CheckCircle,
  AccessTime,
  CalendarToday,
  Person,
  AttachMoney,
  Description,
  ExpandMore,
  FilterList,
  Search,
  GetApp,
  BarChart,
  Dashboard,
  Settings,
  Building,
  Build,
  Inventory,
  Error,
  Info,
  Home,
  Menu,
  Close,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  MoreHoriz,
  Phone,
  Mail,
  LocationOn,
  Star,
  Favorite,
  Share,
  Bookmark,
  Chat,
  Notifications,
  ExitToApp,
  Refresh,
  Upload,
  Copy,
  OpenInNew,
  Print,
  Fullscreen,
  FullscreenExit,
  VolumeUp,
  VolumeOff,
  PlayArrow,
  Pause,
  Stop,
  SkipNext,
  SkipPrevious,
}

// Additional commonly used icons
export {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Check,
  ChevronDown,
  Folder,
  FolderOpen,
  Globe,
  Lock,
  Unlock,
  Save,
  Trash,
  UserPlus,
  UserMinus,
  Zap,
} from 'lucide-react'
